# https://taskfile.dev

version: '3'

vars:
  COMMIT_MESSAGE: updated node version 

tasks:
  default:
    cmds:
      - git add .
      - git commit -m "{{.COMMIT_MESSAGE}}"
      - git push origin main
